import { useCallback, useState, useEffect } from 'react';
import { useEasyChat } from './useEasyChat';
import { supabase } from '@/integrations/supabase/client';

export const useEasyChatEnhanced = (patientId?: string, selectedAnatomy?: string[]) => {
  const [healthTopics, setHealthTopics] = useState<any[]>([]);

  const easyChatHook = useEasyChat(patientId, selectedAnatomy);

  // Generate topics in real-time as conversation progresses
  const generateTopicsForConversation = useCallback(async (conversationPath: any[]) => {
    if (conversationPath.length < 2) return; // Need at least 2 exchanges
    
    try {
      const conversationContext = conversationPath.map(step => 
        `Q: ${step.question?.question_text || 'Unknown question'} A: ${step.response}`
      ).join('\n');

      console.log('Generating real-time topics for Easy Chat conversation');
      
      const { data: topicsData, error: topicsError } = await supabase.functions.invoke('analyze-easy-chat-topics', {
        body: { 
          conversation_context: conversationContext,
          patient_id: patientId || '',
          conversation_type: 'easy_chat'
        }
      });

      if (!topicsError && topicsData?.topics) {
        console.log('Real-time topics generated:', topicsData.topics);
        setHealthTopics(topicsData.topics);
      }
    } catch (error) {
      console.error('Error generating real-time topics:', error);
    }
  }, [patientId]);

  // Watch conversation path changes and generate topics
  useEffect(() => {
    if (easyChatHook.conversationPath.length >= 2) {
      generateTopicsForConversation(easyChatHook.conversationPath);
    }
  }, [easyChatHook.conversationPath, generateTopicsForConversation]);

  const completeCurrentSession = useCallback(async () => {
    if (!easyChatHook.currentSession) return;

    try {
      // Check if we should complete the session based on AI evaluation
      if (easyChatHook.conversationPath.length >= 3) {
        const shouldComplete = await easyChatHook.checkIfReadyToComplete?.(easyChatHook.conversationPath);
        if (!shouldComplete && easyChatHook.conversationPath.length < 10) {
          console.log('AI suggests continuing the conversation for better health topics');
          return; // Don't complete yet, let the conversation continue
        }
      }

      // Generate final summary and complete session
      await easyChatHook.completeSession(easyChatHook.conversationPath);
      
      // Final topics are already generated by real-time updates
      console.log('Session completed with final topics:', healthTopics);
    } catch (error) {
      console.error('Error completing session:', error);
    }
  }, [easyChatHook, healthTopics]);

  return {
    ...easyChatHook,
    completeCurrentSession,
    healthTopics
  };
};